# Generated by Django 4.2.1 on 2023-09-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="code",
            field=models.CharField(default="no_discount", max_length=50, unique=True),
        ),
    ]
