# Generated by Django 4.2.1 on 2023-05-25 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car_rent", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="client", name="discount",),
        migrations.RemoveField(model_name="client", name="fines",),
        migrations.RemoveField(model_name="client", name="number_of_rents",),
    ]
