# Generated by Django 4.2.1 on 2023-05-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_rent", "0002_remove_client_discount_remove_client_fines_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="image",
            field=models.ImageField(blank=True, upload_to="car/%Y/%m/%d"),
        ),
    ]
