# Generated by Django 4.2.1 on 2023-05-26 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car_rent", "0003_car_image"),
    ]

    operations = [
        migrations.DeleteModel(name="Discount",),
        migrations.DeleteModel(name="Fine",),
    ]
