# Generated by Django 4.2.1 on 2023-09-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_rent", "0005_advertisement"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyPartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="car/%Y/%m/%d")),
                ("link", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=100)),
            ],
        ),
    ]
