# Generated by Django 4.2.1 on 2023-09-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_rent", "0006_companypartner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("title", models.CharField(max_length=100)),
                ("short", models.TextField()),
                ("image", models.ImageField(blank=True, upload_to="car/%Y/%m/%d")),
            ],
        ),
    ]
