# Generated by Django 4.2.1 on 2023-09-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_rent", "0007_article"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("info", models.TextField()),
                ("company_name", models.CharField(max_length=100)),
                ("logo", models.ImageField(blank=True, upload_to="car/%Y/%m/%d")),
                ("video_link", models.CharField(max_length=100)),
                ("certificate", models.TextField()),
                ("requisites", models.TextField()),
                ("company_history", models.TextField()),
            ],
        ),
    ]
