# Generated by Django 4.2.1 on 2023-09-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_rent", "0009_newsarticle"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="Date")),
            ],
        ),
    ]
