# Generated by Django 4.2.1 on 2023-09-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_rent", "0010_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("work_info", models.TextField()),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Enter your phone number", max_length=20
                    ),
                ),
                (
                    "email",
                    models.EmailField(help_text="Enter your email", max_length=254),
                ),
                ("image", models.ImageField(blank=True, upload_to="car/%Y/%m/%d")),
            ],
        ),
    ]
