# Generated by Django 4.2.1 on 2023-05-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_discount_order_discount_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="total_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
